/**
 * New Arrivals Data
 * Eight newly added products across multiple categories.
 */

import type { NewArrivalProduct } from "./new-arrivals.types";

export const newArrivalProducts: NewArrivalProduct[] = [
  {
    id: "iphone-17-pro",
    brand: "Apple",
    name: "iPhone 17 Pro",
    image: "/images/hero/hero-01.png",
    rating: 4.9,
    reviewCount: 1200,
    currentPrice: 1299,
    originalPrice: 1399,
    isNew: true,
    colors: ["#1e293b", "#64748b", "#f8fafc", "#7c3aed"],
    category: "featured",
  },
  {
    id: "galaxy-buds-4",
    brand: "Samsung",
    name: "Galaxy Buds 4 Pro",
    image: "/images/hero/hero-03.png",
    rating: 4.7,
    reviewCount: 890,
    currentPrice: 229,
    originalPrice: 279,
    isNew: true,
    colors: ["#0f172a", "#f8fafc"],
    category: "audio",
  },
  {
    id: "rog-zephyrus-g16",
    brand: "ASUS",
    name: "ROG Zephyrus G16",
    image: "/images/hero/hero-02.png",
    rating: 4.8,
    reviewCount: 560,
    currentPrice: 1999,
    originalPrice: 2299,
    isNew: true,
    colors: ["#0f172a"],
    category: "gaming",
  },
  {
    id: "sony-wf-xm6",
    brand: "Sony",
    name: "WF-1000XM6 Earbuds",
    image: "/images/hero/hero-03.png",
    rating: 4.9,
    reviewCount: 2100,
    currentPrice: 299,
    originalPrice: 349,
    isNew: true,
    colors: ["#0f172a", "#e2e8f0"],
    category: "audio",
  },
  {
    id: "smartwatch-ultra-3",
    brand: "Apple",
    name: "Watch Ultra 3",
    image: "/images/hero/hero-01.png",
    rating: 4.8,
    reviewCount: 780,
    currentPrice: 799,
    originalPrice: 899,
    isNew: false,
    colors: ["#1e293b", "#e2e8f0", "#dc2626"],
    category: "electronics",
  },
  {
    id: "dell-xps-16",
    brand: "Dell",
    name: "XPS 16 OLED",
    image: "/images/hero/hero-02.png",
    rating: 4.7,
    reviewCount: 430,
    currentPrice: 1599,
    originalPrice: 1799,
    isNew: true,
    colors: ["#1e293b", "#f8fafc"],
    category: "featured",
  },
  {
    id: "airpods-max-3",
    brand: "Apple",
    name: "AirPods Max 3",
    image: "/images/hero/hero-01.png",
    rating: 4.8,
    reviewCount: 1500,
    currentPrice: 549,
    originalPrice: 599,
    isNew: true,
    colors: ["#0f172a", "#64748b", "#7c3aed", "#dc2626"],
    category: "audio",
  },
  {
    id: "fashion-sneakers-x1",
    brand: "Nike",
    name: "Air Max Pulse x1",
    image: "/images/hero/hero-03.png",
    rating: 4.6,
    reviewCount: 320,
    currentPrice: 189,
    originalPrice: 219,
    isNew: true,
    colors: ["#1e293b", "#f8fafc", "#dc2626"],
    category: "fashion",
  },
];

