/**
 * Best Selling Products Data
 * Eight top-performing products across multiple categories.
 */

import type { BestSellingProduct } from "./best-selling.types";

export const bestSellingProducts: BestSellingProduct[] = [
  {
    id: "macbook-pro-m4",
    brand: "Apple",
    name: "MacBook Pro M4",
    image: "/images/hero/hero-01.png",
    rating: 4.9,
    reviewCount: 2400,
    currentPrice: 1999,
    originalPrice: 2299,
    isSale: true,
    colors: ["#1e293b", "#64748b", "#f8fafc"],
    category: "featured",
  },
  {
    id: "s25-ultra",
    brand: "Samsung",
    name: "Galaxy S25 Ultra",
    image: "/images/hero/hero-02.png",
    rating: 4.8,
    reviewCount: 1800,
    currentPrice: 1099,
    originalPrice: 1299,
    isSale: true,
    colors: ["#1e293b", "#e2e8f0", "#7c3aed"],
    category: "electronics",
  },
  {
    id: "wh1000xm6",
    brand: "Sony",
    name: "WH-1000XM6",
    image: "/images/hero/hero-03.png",
    rating: 5.0,
    reviewCount: 3200,
    currentPrice: 399,
    originalPrice: 449,
    isSale: true,
    colors: ["#0f172a", "#e2e8f0"],
    category: "audio",
  },
  {
    id: "mx-master-3s",
    brand: "Logitech",
    name: "MX Master 3S",
    image: "/images/hero/hero-01.png",
    rating: 4.8,
    reviewCount: 1500,
    currentPrice: 129,
    originalPrice: 149,
    isSale: true,
    colors: ["#1e293b", "#f8fafc"],
    category: "accessories",
  },
  {
    id: "ipad-air-m3",
    brand: "Apple",
    name: "iPad Air M3",
    image: "/images/hero/hero-02.png",
    rating: 4.7,
    reviewCount: 980,
    currentPrice: 749,
    originalPrice: 799,
    isSale: false,
    colors: ["#64748b", "#e2e8f0", "#7c3aed", "#dc2626"],
    category: "featured",
  },
  {
    id: "galaxy-tab-s10",
    brand: "Samsung",
    name: "Galaxy Tab S10",
    image: "/images/hero/hero-03.png",
    rating: 4.6,
    reviewCount: 720,
    currentPrice: 899,
    originalPrice: 999,
    isSale: true,
    colors: ["#1e293b", "#e2e8f0"],
    category: "electronics",
  },
  {
    id: "airpods-pro-3",
    brand: "Apple",
    name: "AirPods Pro 3",
    image: "/images/hero/hero-01.png",
    rating: 4.9,
    reviewCount: 4100,
    currentPrice: 249,
    originalPrice: 279,
    isSale: false,
    colors: ["#f8fafc"],
    category: "audio",
  },
  {
    id: "ps5-pro",
    brand: "Sony",
    name: "PlayStation 5 Pro",
    image: "/images/hero/hero-02.png",
    rating: 4.9,
    reviewCount: 5600,
    currentPrice: 699,
    originalPrice: 799,
    isSale: true,
    colors: ["#0f172a", "#f8fafc"],
    category: "gaming",
  },
];

