import type { Testimonial } from "./testimonials.types";

export const testimonials: Testimonial[] = [
  {
    id: 1,
    name: "Sarah Johnson",
    avatar: "",
    location: "New York, USA",
    rating: 5,
    text: "The quality exceeded my expectations. Fast delivery and excellent packaging. Will definitely buy again!",
    product: "MacBook Pro M4",
    date: "2 days ago",
    isVerified: true,
  },
  {
    id: 2,
    name: "Ahmed Hassan",
    avatar: "",
    location: "Dubai, UAE",
    rating: 5,
    text: "Excellent customer service and top-notch products. The Samsung Galaxy S25 Ultra is incredible!",
    product: "Galaxy S25 Ultra",
    date: "1 week ago",
    isVerified: true,
  },
  {
    id: 3,
    name: "Emma Williams",
    avatar: "",
    location: "London, UK",
    rating: 5,
    text: "Love my new AirPods Pro! The sound quality is amazing and the noise cancellation is a game-changer.",
    product: "AirPods Pro 2",
    date: "Today",
    isVerified: true,
  },
  {
    id: 4,
    name: "Michael Chen",
    avatar: "",
    location: "Toronto, Canada",
    rating: 5,
    text: "Best online shopping experience! The PlayStation 5 arrived in perfect condition and setup was a breeze.",
    product: "PlayStation 5",
    date: "3 days ago",
    isVerified: true,
  },
  {
    id: 5,
    name: "Lisa Park",
    avatar: "",
    location: "Seoul, South Korea",
    rating: 4,
    text: "Great selection of products and competitive prices. The shipping was faster than expected!",
    product: "Dell XPS 16",
    date: "5 days ago",
    isVerified: true,
  },
  {
    id: 6,
    name: "James Rodriguez",
    avatar: "",
    location: "Madrid, Spain",
    rating: 5,
    text: "I&apos;ve been a loyal customer for years. ElectroMart never disappoints with their quality and service.",
    product: "Apple Watch Ultra 2",
    date: "1 week ago",
    isVerified: true,
  },
];

